// Mocks generated by Mockito 5.4.6 from annotations
// in elena_app/test/services/food_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:elena_app/src/features/nutrition/data/repositories/food_repository.dart'
    as _i3;
import 'package:elena_app/src/features/nutrition/data/repositories/food_suggestions_repository.dart'
    as _i6;
import 'package:elena_app/src/features/nutrition/domain/entities/food_model.dart'
    as _i5;
import 'package:elena_app/src/features/nutrition/domain/entities/food_suggestion.dart'
    as _i7;
import 'package:elena_app/src/features/profile/data/user_repository.dart'
    as _i8;
import 'package:elena_app/src/shared/domain/models/health_plan.dart' as _i10;
import 'package:elena_app/src/shared/domain/models/user_food_preferences.dart'
    as _i2;
import 'package:elena_app/src/shared/domain/models/user_model.dart' as _i9;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeUserFoodPreferences_0 extends _i1.SmartFake
    implements _i2.UserFoodPreferences {
  _FakeUserFoodPreferences_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [FoodRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockFoodRepository extends _i1.Mock implements _i3.FoodRepository {
  @override
  _i4.Future<_i5.FoodModel?> getFoodMetadata(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFoodMetadata,
          [query],
        ),
        returnValue: _i4.Future<_i5.FoodModel?>.value(),
        returnValueForMissingStub: _i4.Future<_i5.FoodModel?>.value(),
      ) as _i4.Future<_i5.FoodModel?>);

  @override
  _i4.Future<List<_i5.FoodModel>> getFoodsByCategory(String? category) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFoodsByCategory,
          [category],
        ),
        returnValue: _i4.Future<List<_i5.FoodModel>>.value(<_i5.FoodModel>[]),
        returnValueForMissingStub:
            _i4.Future<List<_i5.FoodModel>>.value(<_i5.FoodModel>[]),
      ) as _i4.Future<List<_i5.FoodModel>>);

  @override
  _i4.Future<List<_i5.FoodModel>> getAllFoods() => (super.noSuchMethod(
        Invocation.method(
          #getAllFoods,
          [],
        ),
        returnValue: _i4.Future<List<_i5.FoodModel>>.value(<_i5.FoodModel>[]),
        returnValueForMissingStub:
            _i4.Future<List<_i5.FoodModel>>.value(<_i5.FoodModel>[]),
      ) as _i4.Future<List<_i5.FoodModel>>);

  @override
  _i4.Future<void> seedInitialNutritionData() => (super.noSuchMethod(
        Invocation.method(
          #seedInitialNutritionData,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [FoodSuggestionsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockFoodSuggestionsRepository extends _i1.Mock
    implements _i6.FoodSuggestionsRepository {
  @override
  _i4.Future<List<_i7.FoodSuggestion>> getSuggestionsByCategory({
    required String? userId,
    required String? category,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSuggestionsByCategory,
          [],
          {
            #userId: userId,
            #category: category,
          },
        ),
        returnValue:
            _i4.Future<List<_i7.FoodSuggestion>>.value(<_i7.FoodSuggestion>[]),
        returnValueForMissingStub:
            _i4.Future<List<_i7.FoodSuggestion>>.value(<_i7.FoodSuggestion>[]),
      ) as _i4.Future<List<_i7.FoodSuggestion>>);

  @override
  _i4.Future<void> markAsShown(
    String? userId,
    List<String>? ids,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #markAsShown,
          [
            userId,
            ids,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> savePersonalizedPool(
    String? userId,
    List<_i7.FoodSuggestion>? pool,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #savePersonalizedPool,
          [
            userId,
            pool,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> addToDaily({
    required String? uid,
    required _i7.FoodSuggestion? suggestion,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addToDaily,
          [],
          {
            #uid: uid,
            #suggestion: suggestion,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [UserRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserRepository extends _i1.Mock implements _i8.UserRepository {
  @override
  _i4.Future<void> saveUser(_i9.UserModel? user) => (super.noSuchMethod(
        Invocation.method(
          #saveUser,
          [user],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i9.UserModel?> getUser([String? uid]) => (super.noSuchMethod(
        Invocation.method(
          #getUser,
          [uid],
        ),
        returnValue: _i4.Future<_i9.UserModel?>.value(),
        returnValueForMissingStub: _i4.Future<_i9.UserModel?>.value(),
      ) as _i4.Future<_i9.UserModel?>);

  @override
  _i4.Stream<_i9.UserModel?> watchUser(String? uid) => (super.noSuchMethod(
        Invocation.method(
          #watchUser,
          [uid],
        ),
        returnValue: _i4.Stream<_i9.UserModel?>.empty(),
        returnValueForMissingStub: _i4.Stream<_i9.UserModel?>.empty(),
      ) as _i4.Stream<_i9.UserModel?>);

  @override
  _i4.Future<void> saveHealthPlan(
    String? uid,
    _i10.HealthPlan? plan,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveHealthPlan,
          [
            uid,
            plan,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Stream<Map<String, dynamic>?> userActivePlanStream(String? uid) =>
      (super.noSuchMethod(
        Invocation.method(
          #userActivePlanStream,
          [uid],
        ),
        returnValue: _i4.Stream<Map<String, dynamic>?>.empty(),
        returnValueForMissingStub: _i4.Stream<Map<String, dynamic>?>.empty(),
      ) as _i4.Stream<Map<String, dynamic>?>);

  @override
  _i4.Future<void> updateUser(
    String? uid,
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateUser,
          [
            uid,
            data,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> saveBodyLog(
    String? uid,
    Map<String, double>? metrics, {
    DateTime? date,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveBodyLog,
          [
            uid,
            metrics,
          ],
          {#date: date},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Stream<List<Map<String, dynamic>>> bodyLogsStream(String? uid) =>
      (super.noSuchMethod(
        Invocation.method(
          #bodyLogsStream,
          [uid],
        ),
        returnValue: _i4.Stream<List<Map<String, dynamic>>>.empty(),
        returnValueForMissingStub:
            _i4.Stream<List<Map<String, dynamic>>>.empty(),
      ) as _i4.Stream<List<Map<String, dynamic>>>);

  @override
  _i4.Future<void> recordFirstMeal(
    String? uid,
    String? option,
    DateTime? time,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #recordFirstMeal,
          [
            uid,
            option,
            time,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Stream<Map<String, dynamic>?> watchUserRaw(String? uid) =>
      (super.noSuchMethod(
        Invocation.method(
          #watchUserRaw,
          [uid],
        ),
        returnValue: _i4.Stream<Map<String, dynamic>?>.empty(),
        returnValueForMissingStub: _i4.Stream<Map<String, dynamic>?>.empty(),
      ) as _i4.Stream<Map<String, dynamic>?>);

  @override
  _i4.Future<void> saveUserFoodPreferences(
    String? uid,
    _i2.UserFoodPreferences? prefs,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveUserFoodPreferences,
          [
            uid,
            prefs,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i2.UserFoodPreferences> getUserFoodPreferences(String? uid) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserFoodPreferences,
          [uid],
        ),
        returnValue: _i4.Future<_i2.UserFoodPreferences>.value(
            _FakeUserFoodPreferences_0(
          this,
          Invocation.method(
            #getUserFoodPreferences,
            [uid],
          ),
        )),
        returnValueForMissingStub: _i4.Future<_i2.UserFoodPreferences>.value(
            _FakeUserFoodPreferences_0(
          this,
          Invocation.method(
            #getUserFoodPreferences,
            [uid],
          ),
        )),
      ) as _i4.Future<_i2.UserFoodPreferences>);

  @override
  _i4.Stream<_i2.UserFoodPreferences> watchUserFoodPreferences(String? uid) =>
      (super.noSuchMethod(
        Invocation.method(
          #watchUserFoodPreferences,
          [uid],
        ),
        returnValue: _i4.Stream<_i2.UserFoodPreferences>.empty(),
        returnValueForMissingStub: _i4.Stream<_i2.UserFoodPreferences>.empty(),
      ) as _i4.Stream<_i2.UserFoodPreferences>);

  @override
  _i4.Future<void> deleteUser(String? uid) => (super.noSuchMethod(
        Invocation.method(
          #deleteUser,
          [uid],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
