// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjutyeWEfZyN2pqmEgM1aEEdidKyekLtk',
    appId: '1:193971045461:web:3a41b03715869ac1cb00dc',
    messagingSenderId: '193971045461',
    projectId: 'elena-app-2026-v1',
    authDomain: 'elena-app-2026-v1.firebaseapp.com',
    storageBucket: 'elena-app-2026-v1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNicPVkyUeEfiYFZHhqah7ZwOkAEr94tw',
    appId: '1:193971045461:android:7845d31793f02c1ecb00dc',
    messagingSenderId: '193971045461',
    projectId: 'elena-app-2026-v1',
    storageBucket: 'elena-app-2026-v1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUPf0Y4ZKPNiqfyo8oZ9RV2r4svyAi5Qs',
    appId: '1:193971045461:ios:bf01fe9e9b74ec41cb00dc',
    messagingSenderId: '193971045461',
    projectId: 'elena-app-2026-v1',
    storageBucket: 'elena-app-2026-v1.firebasestorage.app',
    iosBundleId: 'com.example.elenaApp',
  );

}